call setupenv.bat

cd %BUILD_DIR%
mkdir %TOOLCHAINTAG%
cd %TOOLCHAINTAG%

%CMAKE% %CMAKEGENERATOR% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% %PROJECT_ROOT_DIR%
%CMAKE% --build . --config %BUILD_TYPE%
cd %SCRIPTS_DIR%