language: cpp

branches:
  only:
  - master

os:
- linux
- osx

notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always

compiler: clang++

script:
- mkdir build && cd build
- cmake ..
- make
- cd ..
- mkdir datasets
- curl -o datasets/set1.mdf https://sdlpublic.blob.core.windows.net/datasets/set1.mdf
- ./bin/test_dataserver -i ./datasets/set1.mdf
