language: cpp

branches:
  only:
  - master

os:
- linux
- osx

compiler: clang++

script:
- mkdir build && cd build
- cmake ..
- make
- cd ..
- mkdir datasets
- curl -o datasets/set1.mdf https://sdlpublic.blob.core.windows.net/datasets/set1.mdf
- ./bin/maintest 
- ./bin/test_dataserver -i ./datasets/set1.mdf -b 0 -s 0 -u 1 -a 1 -r 10 -v 1 -x 40 --silence 0
