. ./setup_env.sh

export DATASERVER_BUILD_DIR=${BUILD_DIR}/${CMAKE_BUILD_TYPE}
mkdir -p ${DATASERVER_BUILD_DIR}
cd ${DATASERVER_BUILD_DIR}

#export SDL_BOOST_INCLUDES=/usr/local/include
#export SDL_BOOST_LIBS=/usr/local/lib
#cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DSDL_BOOST_INCLUDES=${SDL_BOOST_INCLUDES} -DSDL_BOOST_LIBS=${SDL_BOOST_LIBS} ${PROJECT_ROOT_DIR}
cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ${PROJECT_ROOT_DIR}
cmake --build . --config ${CMAKE_BUILD_TYPE}
cd ${SCRIPTS_DIR}
