echo DEPLOY_BUILD_TYPE=${DEPLOY_BUILD_TYPE}

if [ ${DEPLOY_BUILD_TYPE} ]
then
export CMAKE_BUILD_TYPE=${DEPLOY_BUILD_TYPE}
else
export CMAKE_BUILD_TYPE=Release
fi

export SCRIPTS_DIR=$(pwd)
export PROJECT_ROOT_DIR=${SCRIPTS_DIR}/..

export BUILD_SUBDIR=build/${CMAKE_BUILD_TYPE}
export BUILD_DIR=${PROJECT_ROOT_DIR}/build