// version.h
//
#pragma once
#ifndef __SDL_SYSTEM_VERSION_H__
#define __SDL_SYSTEM_VERSION_H__

// This file is automatically generated during CMake build process.
// Do not modify version.h -- YOUR CHANGES WILL BE ERASED!
// To update current version make changes in CMakeLists.txt.

#define SDL_DATASERVER_VERSION_MAJOR        1
#define SDL_DATASERVER_VERSION_MINOR        0
#define SDL_DATASERVER_VERSION_REVISION     18
#define SDL_DATASERVER_VERSION              "1.0.18"
#define SDL_DATASERVER_TIMESTAMP            "1519995636"

#endif  // __SDL_SYSTEM_VERSION_H__
